### ISSUE TITLE
Unredable elements with Light theme active

### ISSUE THREAD

**Issue by disshishkov** [dnbard/brackets-projects#9]
The gold filters are unreadable in light theme
![9_1](https://cloud.githubusercontent.com/assets/946095/4642745/89b90076-5448-11e4-87cd-83122fe015ba.png)

I'd prefer black filters (and gray when they are disabled), but not sure that they will be good in black theme
![9_2](https://cloud.githubusercontent.com/assets/946095/4642762/b4abae14-5448-11e4-951e-c598aed2669b.png)

**Comment by dnbard** [comment]
fixed in #15
